#author Jan Matula
#created on 30/03/22
#this is yml file of the conda environment to run the provided script
#first run: conda env create -f environment.yml
#then activate the environment: conda activate cartilage-seg-environment

name: cartilage-seg-environment

channels:
  - defaults

dependencies:
  - ipython=7.19.0
  - h5py=2.9.0
  - tensorflow-gpu=2.1.0
  - tensorflow-estimator=2.1.0
  - keras=2.3.1
  - pillow=6.2.1
  - numpy=1.16.6                                
  - matplotlib=3.3.1
  - ipywidgets=7.5.1
  - python=3.7.9
